### ISSUE TITLE
Install of extra packages not working: environment.yml not used?

### ISSUE THREAD

**Issue by taylorgibson** [jupyterlite/xeus-python-demo#25]
## Description

It doesn't appear that adding libraries to the `environment.yml` file pre-installs extra packages to the environment as intended.

## Reproduce

1. Add a library (e.g. `pandas`) to the `environment.yml` file
2. Wait for github actions to complete
3. Attempt to import library (e.g. `import pandas as pd`)
4. See error, `ModuleNotFoundError: No module named 'pandas'`

## Expected behavior

This should load the library as intended and outlined in [README.md](https://github.com/jupyterlite/xeus-python-demo#readme) and @jtpio's [Jupytercon video](https://youtu.be/8LfnsmtXHNU?t=696).

## Context

- JupyterLite version: 0.1.0
- Using GitHub actions to build and deploy. [Repo](https://github.com/taylorgibson/test-xeus) and [GitHub Page](https://taylorgibson.github.io/test-xeus/lab/index.html)
- Looking at the action logs, it never looks like the `environment.yml` file is used, only the `build-environment.yml` is used to create an environment.

**Comment by jtpio** [comment]
I updated the version of `jupyterlite-xeus-python` in https://github.com/jupyterlite/xeus-python-demo/pull/26, if you would like to apply the same change to your deployment.

**Comment by taylorgibson** [comment]
I can confirm that this now allows packages to be installed. Thanks!

**Comment by jtpio** [comment]
Great, thanks for checking!

**Comment by parthi2929** [comment]
For [my repo](https://github.com/parthi2929/sujan-industries-2), created from latest, its the below and still no package in `environment.yml` gets installed.  

**build-environment.yml**  
```yml
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
```

**environment.yml**  
```yml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - matplotlib
  - pandas
  - networkx
  - ipywidgets
  - pyvis
```

I still get none of above including pandas not detected in browser jupyter lite, notebook.
